### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by joekinley** [karlitos/KissMyResume#18]
When I try to install through `npm install -g kiss-my-resume` I get an error due to puppeteer problems

```
/app # npm install -g kiss-my-resume
/usr/local/bin/kissmyresume -> /usr/local/lib/node_modules/kiss-my-resume/cli.js

> puppeteer@1.20.0 install /usr/local/lib/node_modules/kiss-my-resume/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r686378! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/kiss-my-resume/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/kiss-my-resume/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/kiss-my-resume/node_modules/puppeteer/install.js:64:16)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/local/lib/node_modules/kiss-my-resume/node_modules/puppeteer/.local-chromium'
}
npm WARN promised-handlebars@2.0.1 requires a peer of handlebars@3||4 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.20.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.20.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-10-08T12_01_06_137Z-debug.log
```

I do that within a docker image as follows:

```
FROM node:alpine

ENV APP_HOME /app

RUN npm install -g kiss-my-resume

VOLUME $APP_HOME
WORKDIR $APP_HOME

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["start"]

```

**Comment by ryneeverett** [comment]
As a workaround one can `npm install handlebars`.

**Comment by karlitos** [comment]
Hi, thanks for reporting this issue. I am suprised, that installation of `handlebars` solved this issue. The error comes from missing write permission when installing `puppeteer`

`Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/kiss-my-resume/node_modules/puppeteer/.local-chromium'`

I never tried to install this project on docker, but I might give it a try.
